# .rubocop.yml
AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.2

Layout/LineLength:
  Max: 140

Gemspec/RequireMFA:
  Enabled: false

Gemspec/DevelopmentDependencies:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
